### ISSUE TITLE
Listing on Django Packages.

### ISSUE THREAD

**Issue by lovelydinosaur** [nrocco/djenerics#1]
Whenever you're happy to make this public it'd be worth adding to [the REST framework grid on Django Packages](https://www.djangopackages.com/grids/g/django-rest-framework/).

:smile:

**Comment by nrocco** [comment]
I would be honered if you do that. 

Let me make sure all the code is proper and I will get back to you.

## 

Nico Di Rocco

**Comment by lovelydinosaur** [comment]
> I would be honered if you do that.

Not something you'll need me for - you can add the package yourself. Just go to the homepage of Django Package, hit the 'Add package link', and once the package is listed, add it to the REST framework grid.

No rush. but figured it'd be worth raising as a reminder :)

**Comment by nrocco** [comment]
@tomchristie done. I added it to the grid of the django rest framework. thanks for pointing that out.

**Comment by lovelydinosaur** [comment]
:+1:
